config/routes.rb
Rails.application.routes.draw do
  get 'words/update'

  resources :projects do
    post 'import', :action => 'import_yaml'
    get 'export/:language', :action => 'export_yaml', as: :export
    member do
      get 'translate/:target_language', :action => 'translate', as: :translate
      post 'translate/:target_language', :action => 'translate', as: :translate_second_ref
      get 'show_collaborators', :action => 'show_collaborators', as: :show_collaborators
      post 'add_collaborator', :action => 'add_collaborator', as: :add_collaborator
      delete 'remove_collaborator/:assignment', :action => 'remove_collaborator', as: :remove_collaborator
    end
  end

  devise_for :users
  root :to => 'pages#home'
  get 'pages/home'

  resources :words, only: [:update] do
    get 'translate', :action => 'translate'
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :language
  has_and_belongs_to_many :languages
  has_many :assignments
  has_many :users, through: :assignments
  has_many :words

  after_initialize :init

  def init
    # Default language should be English for new projects
    self.language = Language.find_by_locale('en')
  end

  def reference_words
    get_words language
  end

  def get_words(language)
    words.where language: language
  end

  def get_progress(language)
    allwords = get_words(self.language)
    allwords = allwords.where('text!=""')
    finished_words = 0
    words = get_words(language)
    words.each do |word|
      finished_words += 1 unless(word.text.empty?)
    end
    return 100 if allwords.length == 0
    ((finished_words*1.0/allwords.length*1.0)*100).round
  end

  def add_user(user, role)
    self.assignments << Assignment.new(user: user, role_id: role)
  end
end

app/controllers/projects_controller.rb
#require 'yaml'

class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :translate]
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
    @languages = @project.languages
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      @project.add_user(current_user, Role::PROJECTADMIN)

      redirect_to @project, notice: I18n.t('projects.new.success')
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: I18n.t('projects.edit.success')
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.assignments.destroy_all
    @project.words.destroy_all
    @project.destroy
    redirect_to projects_url, notice: I18n.t('projects.delete.success')
  end

  def translate
    @ref_language = @project.language
    @target_language = Language.find(params[:target_language])
    @second_ref_language = nil
    if params.has_key?(:second_ref_language) and not params[:second_ref_language].empty?
      @second_ref_language = Language.find(params[:second_ref_language])
    end

    @target_words = @project.get_words(@target_language)
    if params.has_key?(:filter) and not params[:filter].empty?
      @filter = params[:filter]
    end
  end

  def import_yaml
    @project = Project.find(params[:project_id])
    uploaded_file = params[:file]
    if '.yml' != File.extname(uploaded_file.original_filename)
      redirect_to project_path(@project), alert: I18n.t('projects.import.use_yaml')
      return
    end
    yaml = YAML::load(uploaded_file.read)

    # Remove old reference words
    if params.has_key? :removeold
      @project.reference_words.delete_all
    end

    ProjectsHelper.import_yaml_hash yaml, @project, ''
    redirect_to project_path(@project), notice: I18n.t('projects.import.success')
  end

  def export_yaml
    language = Language.find (params[:language])
    project = Project.find(params[:project_id])
    project.reference_words.each do |word|
      WordsHelper.get_word_safe project, language, word.key
    end
    root_word = (Word.find_by_language_id language).root
    hash = ProjectsHelper.language_to_yaml_hash root_word
    yaml_hash = Hash.new
    yaml_hash[language.locale] = hash
    send_data yaml_hash.to_yaml, filename: language.locale + '.yml'
  end

  def show_collaborators
    @roles = Role.get_roles
  end

  def add_collaborator
    user = User.find_by_email(params[:email])
    unless user
      redirect_to show_collaborators_project_url(@project), notice: I18n.t('projects.collaborator.notfound', email: params[:email])
      return
    end
    if @project.assignments.where({role_id: params[:role_id], user: user}).any?
      # User already has this role
      redirect_to show_collaborators_project_url(@project), notice: I18n.t('projects.collaborator.assigned', email: params[:email], project: @project.name)
      return
    end

    # Finally add the user to the project
    if @project.add_user(user, params[:role_id])
      redirect_to show_collaborators_project_url(@project), notice: I18n.t('projects.collaborator.added', email: params[:email], project: @project.name)
    else
      redirect_to show_collaborators_project_url(@project), notice: I18n.t('projects.collaborator.notadded', email: params[:email], project: @project.name)
    end
  end

  def remove_collaborator
    if Assignment.delete(params[:assignment])
      redirect_to show_collaborators_project_url(@project), notice: I18n.t('projects.collaborator.deleted')
    else
      redirect_to show_collaborators_project_url(@project), notice: I18n.t('projects.collaborator.notdeleted')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :language_id, :language_ids => [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def self.import_yaml_hash hash, project, currentkey
    cur = currentkey
    hash.each_pair do |k, v|
      if(v.is_a? Hash)
        import_yaml_hash v, project, cur+k+':'
      else
        Word.create_word cur+k, v, project, project.language
      end
    end
  end

  def filter_options
    [
        [t('projects.translate.untranslated'), 'untranslated'],
        [t('projects.translate.translated'), 'translated']
    ]
  end

  def self.language_to_yaml_hash word
    hash = Hash.new;
    if word.has_children?
       word.children.each do |child|
         hash[child.key.rpartition(':')[2]] = language_to_yaml_hash child
       end
      return hash
    else
      return word.text
    end
  end
end

app/views/projects/_form.html.slim
= bootstrap_form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field
    = f.text_field :name
  .actions
    - if @project.new_record?
      = link_to_button(projects_path(), :back)
    - else
      = link_to_button(project_path(@project), :back)
    = link_to_button(nil, :save)

app/views/projects/_infobar.html.slim
.page-header
  - if current_page?(project_path(@project))
      h1.projectname
        = @project.name
  - else
      h3.projectname
        = link_to icon('chevron-left', @project.name), project_path(@project)
  - if can? :manage, @project
    .btn-group.pull-right
      button.btn.btn-default.dropdown-toggle data-toggle="dropdown"
        = icon('gear')
      ul.dropdown-menu role="menu"
        li
          = link_to raw(icon('upload', t('projects.show.import_yaml'))), '', modal_options('#import_yaml')
        li
          = link_to raw(icon('users', t('projects.show.managecollaborators'))), show_collaborators_project_path(@project)
        li
          = link_to raw(icon('hand-o-right', t('projects.show.target_lang'))), '', modal_options('#targetlang')
        li
          = link_to raw(icon('info', t('projects.show.ref_lang'))), '', modal_options('#reflang')
        li
          = link_to raw(icon('pencil-square-o', t('projects.show.edit'))), edit_project_path(@project)
        li
          = link_to raw(icon('trash', t('projects.show.delete'))), @project, data: {:confirm => t('projects.show.delete_question')}, :method => :delete

/ Modals made with the help of http://stackoverflow.com/questions/20662793/bootsrap-3-modal-with-rails-4-not-showing/20693907#20693907
/ Modal dialogs
= render partial: 'modal_import_yaml'
= render partial: 'modal_targetlang'
= render partial: 'modal_reflang'

app/views/projects/_modal_import_yaml.html.slim
.modal.fade#import_yaml
  .modal-dialog
    .modal-content
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal" aria-hidden="true" ×
        h3 id="myModalLabel"
          = t('projects.show.import_yaml')
      div class="modal-body"
        = form_tag project_import_path(@project), remote: true, multipart: true, accept: ".yml" , authenticity_token: true do
          .checkbox
            label for='removeold'
              = check_box_tag('removeold', '1', false)
              = t('projects.show.remove_old')
          = file_field_tag 'file', accept: '.yml'
          div class="modal-footer"
            button class="btn" data-dismiss="modal" aria-hidden="true"
              = t('general.back')
            = submit_tag t('general.import'), class: 'btn btn-primary'

app/views/projects/_modal_reflang.html.slim
.modal.fade#reflang
  .modal-dialog
    .modal-content
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal" aria-hidden="true" ×
        h3 id="myModalLabel"
          = t('projects.show.ref_lang')
      div class="modal-body"
        = form_for @project do |f|
          = f.select(:language_id, Language.all.map {|l| [l.get_full_name, l.id]}, {},  class: 'form-control')
          div class="modal-footer"
            button class="btn" data-dismiss="modal" aria-hidden="true"
              = t('general.back')
            button type="submit" class="btn btn-primary"
              = t('general.save')

app/views/projects/_modal_targetlang.html.slim
.modal.fade#targetlang
  .modal-dialog
    .modal-content
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal" aria-hidden="true" ×
        h3 id="myModalLabel"
          = t('projects.show.target_lang')
      div class="modal-body"
        = form_for @project do |f|
          = f.select(:language_ids, Language.all.map {|l| [l.name + " - " + l.locale, l.id]}, {}, {multiple: true, size: 10, class: 'form-control'})
          div class="modal-footer"
            button class="btn" data-dismiss="modal" aria-hidden="true"
              = t('general.back')
              button type="submit" class="btn btn-primary"
                = t('general.save')

app/views/projects/edit.html.slim
== render partial: 'infobar'

== render 'form'

app/views/projects/index.html.slim
.page-header
  h1 = t '.heading'

- @projects.each do |project|
  - if cannot? :read, project
    - next
  .media
    .media-body
      h2.media-heading
        = link_to project.name, project

br

- if can? :create, Project
  = link_to_button(new_project_path, :new)

app/views/projects/new.html.slim
.page-header
  h1 = t('.heading')

== render 'form'

app/views/projects/show.html.slim
== render partial: 'infobar'

- if can? :manage, @project and (@languages.empty? or @project.words.empty?)
  h3 = t('.get_started')
  ul
    - if @project.words.empty?
      li
        = link_to t('.import_words'), '', modal_options('#import_yaml')
    - if @languages.empty?
      li
        = link_to t('.add_target_lang'), '', modal_options('#targetlang')

- if can? :read, @project and not @languages.empty?
  table class="table table-striped"
    thead
      tr
        th.project
        th.progressbar
        th.download
    tbody
      - @languages.each do |language|
        tr
          td style="min-width: 30%; white-space: nowrap;"
            .media
              .media-body
                h3.media-heading
                  = link_to language.name, translate_project_path(@project, language)
          - percentage = @project.get_progress(language)
          td
            .progress
              div class="progress-bar progress-bar-success progress-bar-striped" aria-valuenow="#{percentage}" aria-valuemin="0" aria-valuemax="100" style="width: #{percentage}%; font-weight:bold;"
                = "#{percentage}% " + t('.completed')
              div class="progress-bar progress-bar-danger progress-bar-striped" aria-valuenow="#{100-percentage}" aria-valuemin="0" aria-valuemax="100" style="width: #{100-percentage}%"
                span class="sr-only"
                  |#{100-percentage}% Complete (danger)
          td
            = link_to raw(icon('download')), project_export_path(@project, language), class: 'normalbtn', title: t('.download_yaml')

app/views/projects/show_collaborators.slim
== render partial: 'infobar'

h2 = t('projects.show.addcollaborator')
= form_tag(add_collaborator_project_path(@project), method: :post)
  .form-inline role="form"
    .form-group
      .input-group
        .input-group-addon @
        input.form-control type="email" placeholder="#{t('projects.show.collabemail')}" name="email"
    .form-group
      select.form-control name="role_id"
        = options_for_select(@roles)
      = submit_tag(t('general.add'), class: 'savebtn')

table.table.table-striped.table-hover
  thead
    tr
      th = t('user.title')
      th = t('role.title')
      th
  tbody
    - @project.assignments.each do |assignment|
      tr
        td = assignment.user.email
        td = Role.get_role_name(assignment.role.id)
        td = link_to icon('trash'), remove_collaborator_project_path(@project, assignment), :method => :delete, :title => t('general.remove')

app/views/projects/translate.html.slim
== render partial: 'infobar'

= form_tag(translate_second_ref_project_path, class: 'form-inline')
  = select_tag('second_ref_language', options_from_collection_for_select(@project.languages, 'id', 'get_full_name',
          (@second_ref_language.id if @second_ref_language)),
          prompt: t('.select_ref_lang'), onchange: 'this.form.submit()', class: 'form-control')
  = select_tag('filter', options_for_select(filter_options, (@filter if @filter)), onchange: 'this.form.submit()',
          prompt: t('.filter_all'), class: 'form-control')
table.table.table-striped.table-hover
  thead
    tr
      th.reference
        = @ref_language.name
        - if @second_ref_language
          br
          i
            = @second_ref_language.name
      th.target
        = @target_language.name
      - if can? :translate, Word
        th.translate

  - @project.reference_words.each do |word|
    - if word.text.empty?
      - next
    - target_word = WordsHelper.get_word_safe @project, @target_language, word.key
    - if @filter == 'translated' and target_word.text.empty?
      - next
    - elsif @filter == 'untranslated' and not target_word.text.empty?
      - next
    tr
      td
        b
          = word.text
        - if @second_ref_language
          br
          i
            = WordsHelper.get_word_safe(@project, @second_ref_language, word.key).text
        td
          = bootstrap_form_for target_word, remote: true, url: word_path(target_word), method: :patch do |f|
            = f.text_field :text, class: 'form-control words_onchange', id: "word_#{target_word.id}", hide_label: true
        - if can? :translate, Word
          td = link_to icon('magic'), word_translate_path(target_word), remote: true, class: 'normalbtn translatebtn', id: "btn_#{target_word.id}", title: t('projects.show.translate_bing')