config/routes.rb
Rails.application.routes.draw do
  get 'words/update'

  resources :projects do
    post 'import', :action => 'import_yaml'
    get 'export/:language', :action => 'export_yaml', as: :export
    member do
      get 'translate/:target_language', :action => 'translate', as: :translate
      post 'translate/:target_language', :action => 'translate', as: :translate_second_ref
      get 'show_collaborators', :action => 'show_collaborators', as: :show_collaborators
      post 'add_collaborator', :action => 'add_collaborator', as: :add_collaborator
      delete 'remove_collaborator/:assignment', :action => 'remove_collaborator', as: :remove_collaborator
    end
  end

  devise_for :users
  root :to => 'pages#home'
  get 'pages/home'

  resources :words, only: [:update] do
    get 'translate', :action => 'translate'
  end

end

app/views/layouts/_alerts.html.slim
- if flash[:notice]
  .alert.alert-info
    = flash[:notice]

- if flash[:alert]
  .alert.alert-danger
    = flash[:alert]

app/views/layouts/_menu.html.slim
nav.navbar.navbar-default role="navigation"
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-toggle="collapse" data-target="#navbar-collapse" type="button"
        span.sr-only
          Toggle Navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to raw(icon('magic', 'Rubylator')), pages_home_path, class: 'navbar-brand'
    .collapse.navbar-collapse#navbar-collapse
      ul.nav.navbar-nav
        li
          =link_to raw(icon('folder', t('projects.index.heading'))), projects_path
      - if user_signed_in?
       ul.nav.navbar-nav.navbar-right
         li
           = link_to raw(icon('power-off', t('general.logout'))), destroy_user_session_url, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title Rubylator
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = fontawesome_stylesheet_link_tag :netdna, force: true
    = csrf_meta_tags
  body
    #header
      = render "layouts/menu"
    .container
      #alerts.row
        = render "layouts/alerts"
      #infobar.row
        == yield :infobar
      #content.row
        == yield